title: Website Cookbook
email: charleschoi87@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a group for anyone interested in building side projects. Developers, designers, marketers, executors are welcome. Also, people with only ideas are welcome. Looking forward to meeting a lot of people who make new things. Let’s share an idea and build it!
twitter_username: cycorld
github_username:  cycorld
search_enabled: true

remote_theme: pmarsceill/just-the-docs
